server:
  port: 3344

spring:
  application:
    name: springcloud-config-center
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:WF1683497569/SpringCloud2020.git
          uri: https://github.com/WF1683497569/SpringCloud2020
          skip-ssl-validation: true
          search-paths:
            - springcloud-config
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

# 暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"